### 获取 Token
POST http://127.0.0.1:9001/feather/ecommerce-nacos-client/communication/token-by-feign
Content-Type: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidG9rZW5cIjpcImZlYXRoZXJcIn0iLCJqdGkiOiI2ZDFjOGM0YS1kZjJlLTRjODYtODM5YS00ZTgxNGMyOGQzYjAiLCJleHAiOjE2OTM2NzA0MDB9.k74MMgvkMoIhxNurFuN-EqRZ-Xhy8gFHjdf_Fcv5wVhfUaPDTAuWDeR-6AstMF6jUlQivczQyqlxzwjeunpVO7bFgTMU5jM99m4JH7IUYdqdJJyrPCSX-aqATufIWsow0HtJM_VTjzFFtQk5WFVNXPsd07iTRz-Xsfwz34P-7WhVkqgUTqYwZ47GNobA-6jAx7CkDjx5ClTm2DuuS94ZWaPLjiI_8fBOHKYWN2tMwx0Sl-4DxKvgr0Ja7JiNmYpdl815WvKJuZv3-FmWi71EZwwRaIrYTfpdoxm4w7Iawb2G9edgrekIdtb1hf4EKZwF4wECPpiczzRJ23YP8kOr1A
token: feather

{
  "username": "feather",
  "password": "25d55ad283aa400af464c76d713c07ad"
}


### 根据提供的 serviceId 获取实例信息
GET http://127.0.0.1:9001/feather/ecommerce-nacos-client/hystrix/hystrix-command-annotation?serviceId=e-commerce-nacos-client
Content-Type: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidG9rZW5cIjpcImZlYXRoZXJcIn0iLCJqdGkiOiI2ZDFjOGM0YS1kZjJlLTRjODYtODM5YS00ZTgxNGMyOGQzYjAiLCJleHAiOjE2OTM2NzA0MDB9.k74MMgvkMoIhxNurFuN-EqRZ-Xhy8gFHjdf_Fcv5wVhfUaPDTAuWDeR-6AstMF6jUlQivczQyqlxzwjeunpVO7bFgTMU5jM99m4JH7IUYdqdJJyrPCSX-aqATufIWsow0HtJM_VTjzFFtQk5WFVNXPsd07iTRz-Xsfwz34P-7WhVkqgUTqYwZ47GNobA-6jAx7CkDjx5ClTm2DuuS94ZWaPLjiI_8fBOHKYWN2tMwx0Sl-4DxKvgr0Ja7JiNmYpdl815WvKJuZv3-FmWi71EZwwRaIrYTfpdoxm4w7Iawb2G9edgrekIdtb1hf4EKZwF4wECPpiczzRJ23YP8kOr1A
token: feather


### 根据提供的 serviceId 获取实例信息
GET http://127.0.0.1:9001/feather/ecommerce-nacos-client/hystrix/simple-hystrix-command?serviceId=e-commerce-nacos-client
Content-Type: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidG9rZW5cIjpcImZlYXRoZXJcIn0iLCJqdGkiOiI2ZDFjOGM0YS1kZjJlLTRjODYtODM5YS00ZTgxNGMyOGQzYjAiLCJleHAiOjE2OTM2NzA0MDB9.k74MMgvkMoIhxNurFuN-EqRZ-Xhy8gFHjdf_Fcv5wVhfUaPDTAuWDeR-6AstMF6jUlQivczQyqlxzwjeunpVO7bFgTMU5jM99m4JH7IUYdqdJJyrPCSX-aqATufIWsow0HtJM_VTjzFFtQk5WFVNXPsd07iTRz-Xsfwz34P-7WhVkqgUTqYwZ47GNobA-6jAx7CkDjx5ClTm2DuuS94ZWaPLjiI_8fBOHKYWN2tMwx0Sl-4DxKvgr0Ja7JiNmYpdl815WvKJuZv3-FmWi71EZwwRaIrYTfpdoxm4w7Iawb2G9edgrekIdtb1hf4EKZwF4wECPpiczzRJ23YP8kOr1A
token: feather


### 根据提供的 serviceId 获取实例信息
GET http://127.0.0.1:9001/feather/ecommerce-nacos-client/hystrix/hystrix-observable-command?serviceId=e-commerce-nacos-client
Content-Type: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidG9rZW5cIjpcImZlYXRoZXJcIn0iLCJqdGkiOiI2ZDFjOGM0YS1kZjJlLTRjODYtODM5YS00ZTgxNGMyOGQzYjAiLCJleHAiOjE2OTM2NzA0MDB9.k74MMgvkMoIhxNurFuN-EqRZ-Xhy8gFHjdf_Fcv5wVhfUaPDTAuWDeR-6AstMF6jUlQivczQyqlxzwjeunpVO7bFgTMU5jM99m4JH7IUYdqdJJyrPCSX-aqATufIWsow0HtJM_VTjzFFtQk5WFVNXPsd07iTRz-Xsfwz34P-7WhVkqgUTqYwZ47GNobA-6jAx7CkDjx5ClTm2DuuS94ZWaPLjiI_8fBOHKYWN2tMwx0Sl-4DxKvgr0Ja7JiNmYpdl815WvKJuZv3-FmWi71EZwwRaIrYTfpdoxm4w7Iawb2G9edgrekIdtb1hf4EKZwF4wECPpiczzRJ23YP8kOr1A
token: feather
