### 查询服务
GET http://127.0.0.1:9001/feather /ecommerce-nacos-client/nacos-client/service-instance?serviceId=e-commerce-gateway
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEyLFwidG9rZW5cIjpcImZlYXRoZXLlk4jlk4jlk4jlk4hcIn0iLCJqdGkiOiJkMWE2ODY5Zi1mZjZlLTQ5ZTYtOTA4OC05OTgwMGE2NmFlYTUiLCJleHAiOjE2OTExNjQ4MDB9.NHdYnRdUfIF1PdhqkTaI3eTZZAM9_7LjilrMcIqB0CRJ2FRAhjg20KAN5Y_zfzEWDRopSKgk0Q_Y-XFHqxEmZaZ2OyQzX1yK9EAVCmRzS0TGzlMVp0_rXXEOcljZSOoGJ940VeJ2_Z6uwc_QckxDOumB8i5rwAoS2JmftM30w-vrvJ-6WkVW58f6SZBe_uYZEZbzasTE4SKuLF1Xdq5e8ntvMp3mEGUbnB4XuzVFTGf31t3PMP652BZLzgXW1lP8Sh0ojTzGkNCOqgK2UBheDx_XsPmCd_-DYZyw7cXNm1pKEx_oEMkxCz1YilfYoe21lJA9dB6HLiUAbWP8Uw5mWA
token: feather
